### PR TITLE
2014 data update

### PR DESCRIPTION
**Pull request by xavriley**
This isn't quite working yet as all the spv ids are coming out as 1 - any suggestions appreciated!

### CODE REVIEW

**Comment by xavriley** [comment]
Just hacked on this and got it working with the 2014 data. Was inspired by the fact that it's nearly a year since the AccHack!

Could you merge and then perhaps @jms301 could do the honours and update the meteor site?

Hope you are both well!

**Comment by atiro** [comment]
Ack sorry Xav, got distracted with so many other things. Will _definitely_ do this weekend.

**Comment by xavriley** [comment]
Cool. It's all working now so it should just be a simple merge in this repo. Not sure what's involved at the meteor end though

**Comment by atiro** [comment]
Yeah I'm afraid my meteor knowledge never really advanced. Might hack away again on my django version instead

**Comment by jms301** [comment]
Sorry for silence I'm still alive, do you just want to load in new data?
Shouldn't be too hard if so, let me know when / where the files are there.

**Comment by atiro** [comment]
Merged, I think ready for you to load up into pfi-explorer @jms301  ? (hello!)

**Comment by jms301** [comment]
Ok had a look at this today, can't honestly remember how we did the data loading for this! Been a while and I'm gettin old ;) 

Anyway I presume the relevant file for me is projects.json but it doesn't seem to contain any of the payment, spv or equity data?

**Pull request merged**
